### ISSUE TITLE
v. 1.1.3

### ISSUE THREAD

**Issue by xylar** [ACME-Climate/e3sm-unified#5]
Changes in the next version of e3sm-unified:
- nco 4.7.3
- acme_diags 1.2.1
- mpas_analysis 0.7.0
- processflow 1.0.1

**Comment by xylar** [comment]
@zshaheen, @chengzhuzhang, @milenaveneziani:

This is an issues to keep track of changes that will go into the next version of e3sm-unified.  Please add to or correct the above list if need be.

**Comment by zshaheen** [comment]
Thanks @xylar. By the way, when's the ETA for the next release of the unified env? We might have another minor release of `acme_diags` soon.

**Comment by xylar** [comment]
I’ll add a timetable if and when it’s clear that there is a pressing need. So far, acme_diags is the most pressing update, since nco has not yet made the 4.7.3 tag and mpas_analysis hasn’t yet uploaded a conda package (though they’re built and ready to upload).

**Comment by xylar** [comment]
addressed by #8
