### ISSUE TITLE
Add the processflow to unified

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-Climate/e3sm-unified#6]
I would like to add the latest version of the processflow to the next version of the e3sm-unified. Please let me know what you need to get it into the package.

**Comment by xylar** [comment]
@sterlingbaldwin, all I would need to know is the package name, conda channel and version number.  Once I have those, I'll add it to the Confluence page that documents the versions in each E3SM-Unified version and I'll make sure its doesn't cause any issues when I include it in the next version.  Thanks!

**Comment by sterlingbaldwin** [comment]
package name: processflow
channel: acme
version number: 1.0.1

I dont know if you need this, but to do the install it requires the following command:
```
conda install -c acme -c conda-forge -c uvcdat processflow
```

**Comment by xylar** [comment]
addressed by #8
